flowchart LR
    subgraph app
        app__setInvalid["setInvalid"]
        app__form["form"]
        app__validEmail["validEmail"]
        app__validRepo["validRepo"]
    end
    subgraph index
        index__send_notification["send_notification"]
        index__send_notification_smtp["send_notification_smtp"]
        index__env["env"]
    end
    app__form --> app__setInvalid
    app__form --> app__validEmail
    app__form --> app__validRepo
    index__send_notification --> index__env
    index__send_notification --> index__send_notification_smtp
    index__send_notification_smtp --> index__env
