flowchart LR
    subgraph app
        app__validRepo["validRepo"]
        app__validEmail["validEmail"]
        app__setInvalid["setInvalid"]
        app__form["form"]
    end
    subgraph index
        index__send_notification["send_notification"]
        index__env["env"]
        index__send_notification_smtp["send_notification_smtp"]
    end
    subgraph vendor__composer
        vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__findFile["findFile"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalledPackagesByType["getInstalledPackagesByType"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getReference["getReference"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalledPackages["getInstalledPackages"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__isInstalled["isInstalled"]
        vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__initializeIncludeClosure["initializeIncludeClosure"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled["getInstalled"]
        vendor__composer__ClassLoader__Composer_Autoload__ClassLoader____construct["__construct"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getAllRawData["getAllRawData"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__satisfies["satisfies"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getRootPackage["getRootPackage"]
        vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__findFileWithExtension["findFileWithExtension"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getRawData["getRawData"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstallPath["getInstallPath"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getVersionRanges["getVersionRanges"]
        vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__loadClass["loadClass"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getPrettyVersion["getPrettyVersion"]
        vendor__composer__InstalledVersions__Composer__InstalledVersions__getVersion["getVersion"]
    end
    subgraph vendor__phpmailer
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__parseAddresses["parseAddresses"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setMessageType["setMessageType"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login["login"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__utf8CharBoundary["utf8CharBoundary"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getServerExt["getServerExt"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__mail["mail"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSentMIMEMessage["getSentMIMEMessage"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__headerLine["headerLine"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isPermittedPath["isPermittedPath"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__send["send"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand["sendCommand"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLE["setLE"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__rfcDate["rfcDate"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isValidHost["isValidHost"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend["sendmailSend"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer____destruct["__destruct"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_BodyC["DKIM_BodyC"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__popBeforeSmtp["popBeforeSmtp"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString["encodeString"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingWSP["stripTrailingWSP"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang["lang"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getLastReply["getLastReply"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setBoundaries["setBoundaries"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress["validateAddress"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__inlineImageExists["inlineImageExists"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__verify["verify"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__quotedString["quotedString"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__has8bitChars["has8bitChars"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__authenticate["authenticate"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailPassthru["mailPassthru"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat["addrFormat"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__sendString["sendString"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrAppend["addrAppend"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setWordWrap["setWordWrap"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__parseDSN["parseDSN"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__getResponse["getResponse"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__hello["hello"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__alternativeExists["alternativeExists"]
        vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getToken["getToken"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearBCCs["clearBCCs"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addCC["addCC"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer___mime_types["_mime_types"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__secureHeader["secureHeader"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_HeaderC["DKIM_HeaderC"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress["addOrEnqueueAnAddress"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__authorise["authorise"]
        vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getOauth64["getOauth64"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpClose["smtpClose"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage["addStringEmbeddedImage"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__hasLineLongerThanMax["hasLineLongerThanMax"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getTranslations["getTranslations"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__punyencodeAddress["punyencodeAddress"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__disconnect["disconnect"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAnAddress["addAnAddress"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug["edebug"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__xclient["xclient"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearQueuedAddresses["clearQueuedAddresses"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSmtpErrorMessage["getSmtpErrorMessage"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__startTLS["startTLS"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getError["getError"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setFrom["setFrom"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend["smtpSend"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addReplyTo["addReplyTo"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__client_send["client_send"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLanguage["setLanguage"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage["addEmbeddedImage"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isShellSafe["isShellSafe"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getMailMIME["getMailMIME"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundaries["getBoundaries"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mb_pathinfo["mb_pathinfo"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__quit["quit"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundary["getBoundary"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__applyConfig["applyConfig"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachAll["attachAll"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__generateId["generateId"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getSMTPConnection["getSMTPConnection"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__setError["setError"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__catchWarning["catchWarning"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachmentExists["attachmentExists"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile["encodeFile"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend["mailSend"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect["connect"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__checkResponse["checkResponse"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__textLine["textLine"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType["filenameToType"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__noop["noop"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend["preSend"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addressHasUnicodeLocalPart["addressHasUnicodeLocalPart"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__parseUrl["parseUrl"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAddress["addAddress"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__close["close"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader["createHeader"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks["normalizeBreaks"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_Sign["DKIM_Sign"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__parseHelloFields["parseHelloFields"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__get_lines["get_lines"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__recordLastTransactionID["recordLastTransactionID"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__idnSupported["idnSupported"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendAndMail["sendAndMail"]
        vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getGrant["getGrant"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError["setError"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible["fileIsAccessible"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__reset["reset"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__serverHostname["serverHostname"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateEncoding["validateEncoding"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearAddresses["clearAddresses"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addBCC["addBCC"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__errorHandler["errorHandler"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configureOptions["configureOptions"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__mailer["mailer"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearCCs["clearCCs"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addCustomHeader["addCustomHeader"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingBreaks["stripTrailingBreaks"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment["addAttachment"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__set["set"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend["postSend"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configureSMTP["configureSMTP"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment["addStringAttachment"]
        vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configure["configure"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader["encodeHeader"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__wrapText["wrapText"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpConnect["smtpConnect"]
        vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__connect["connect"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__data["data"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSMTPInstance["getSMTPInstance"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__turn["turn"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connected["connected"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody["createBody"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError["setError"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__anyAddressHasUnicodeLocalPart["anyAddressHasUnicodeLocalPart"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__recipient["recipient"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendHello["sendHello"]
        vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug["edebug"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__replaceCustomHeader["replaceCustomHeader"]
        vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeQP["encodeQP"]
    end
    vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getToken --> vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getGrant
    vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getOauth64 --> vendor__phpmailer__phpmailer__src__OAuth__PHPMailer_PHPMailer__OAuth__getToken
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__mailer --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configure
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configure --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__parseDSN
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configure --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__applyConfig
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__parseDSN --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__parseUrl
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__applyConfig --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configureSMTP
    vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__applyConfig --> vendor__phpmailer__phpmailer__src__DSNConfigurator__PHPMailer_PHPMailer__DSNConfigurator__configureOptions
    index__send_notification --> index__env
    index__send_notification --> index__send_notification_smtp
    index__send_notification_smtp --> index__env
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__popBeforeSmtp --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__authorise
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__authorise --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__connect
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__authorise --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__authorise --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__disconnect
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__connect --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__setError
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__connect --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__getResponse
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__connect --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__checkResponse
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__setError
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__sendString
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__getResponse
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__login --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__checkResponse
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__disconnect --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__sendString
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__disconnect --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__getResponse
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__checkResponse --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__setError
    vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__catchWarning --> vendor__phpmailer__phpmailer__src__POP3__PHPMailer_PHPMailer__POP3__setError
    app__form --> app__setInvalid
    app__form --> app__validEmail
    app__form --> app__validRepo
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalledPackages --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalledPackagesByType --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__isInstalled --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__satisfies --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getVersionRanges
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getVersionRanges --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getVersion --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getPrettyVersion --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getReference --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstallPath --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getRootPackage --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getRawData --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getAllRawData
    vendor__composer__InstalledVersions__Composer__InstalledVersions__getAllRawData --> vendor__composer__InstalledVersions__Composer__InstalledVersions__getInstalled
    vendor__composer__ClassLoader__Composer_Autoload__ClassLoader____construct --> vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__initializeIncludeClosure
    vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__loadClass --> vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__findFile
    vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__findFile --> vendor__composer__ClassLoader__Composer_Autoload__ClassLoader__findFileWithExtension
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__client_send
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connected
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getSMTPConnection
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connect --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__get_lines
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getSMTPConnection --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__startTLS --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__authenticate --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__authenticate --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__authenticate --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connected --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connected --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__close
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__close --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__data --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__hello --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendHello
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendHello --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendHello --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__parseHelloFields
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__mail --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__quit --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__quit --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__close
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__recipient --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__xclient --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__reset --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__connected
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__client_send
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__get_lines
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendAndMail --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__verify --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__noop --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__sendCommand
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__turn --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__turn --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__client_send --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getServerExt --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__get_lines --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__errorHandler --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__setError
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__errorHandler --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__edebug
    vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__recordLastTransactionID --> vendor__phpmailer__phpmailer__src__SMTP__PHPMailer_PHPMailer__SMTP__getLastReply
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer____destruct --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpClose
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailPassthru --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__secureHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailPassthru --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailPassthru --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addCC --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addBCC --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addReplyTo --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addOrEnqueueAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setBoundaries --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__generateId
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAnAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__parseAddresses --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setFrom --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__send
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setFrom --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__has8bitChars
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setFrom --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__idnSupported
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setFrom --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__punyencodeAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__idnSupported
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__punyencodeAddress --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__has8bitChars
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__send --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__send --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__send --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLE
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__anyAddressHasUnicodeLocalPart
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addressHasUnicodeLocalPart
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__postSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingWSP
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__sendmailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isShellSafe
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isPermittedPath
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingWSP
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mailSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateAddress
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingWSP
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpConnect
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__preSend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpSend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__smtpConnect --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSMTPInstance
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLanguage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getTranslations --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLanguage
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrAppend --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__secureHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__wrapText --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__wrapText --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__utf8CharBoundary
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setWordWrap --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__wrapText
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__headerLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__rfcDate
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrFormat
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addrAppend
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getMailMIME --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__headerLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getMailMIME --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__textLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSentMIMEMessage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingWSP
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setBoundaries
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getMailMIME
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setWordWrap
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__has8bitChars
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__hasLineLongerThanMax
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundary
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachAll
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__createBody --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__textLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundaries --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setBoundaries
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundary --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__textLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getBoundary --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__headerLine
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setMessageType --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__alternativeExists
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setMessageType --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__inlineImageExists
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setMessageType --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachmentExists
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mb_pathinfo
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateEncoding
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachAll --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__quotedString
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachAll --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__attachAll --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__secureHeader
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeFile --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeQP
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeString --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__has8bitChars
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__encodeQP --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateEncoding
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mb_pathinfo
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringAttachment --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__fileIsAccessible
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateEncoding
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mb_pathinfo
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__validateEncoding
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addStringEmbeddedImage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__edebug
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearAddresses --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearQueuedAddresses
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearCCs --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearQueuedAddresses
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearBCCs --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__clearQueuedAddresses
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__replaceCustomHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__serverHostname --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__isValidHost
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__anyAddressHasUnicodeLocalPart --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addressHasUnicodeLocalPart
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setLanguage
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__getSmtpErrorMessage --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__addCustomHeader --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__mb_pathinfo
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__filenameToType --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer___mime_types
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__set --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__setError
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__set --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_Sign --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__lang
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_HeaderC --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_BodyC --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__normalizeBreaks
    vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__DKIM_BodyC --> vendor__phpmailer__phpmailer__src__PHPMailer__PHPMailer_PHPMailer__PHPMailer__stripTrailingBreaks
