flowchart TD
    admin__auth["admin.auth<br/>2 funcs"]
    admin__logs["admin.logs<br/>3 funcs"]
    api__redsl["api.redsl<br/>4 funcs"]
    app["app<br/>15 funcs"]
    bootstrap["bootstrap<br/>5 funcs"]
    client__index["client.index<br/>1 funcs"]
    config_api["config-api<br/>15 funcs"]
    config_editor["config-editor<br/>5 funcs"]
    email_notifications["email-notifications<br/>4 funcs"]
    index["index<br/>2 funcs"]
    marketing__index["marketing.index<br/>11 funcs"]
    nda_form["nda-form<br/>11 funcs"]
    polityka_prywatnosci["polityka-prywatnosci<br/>1 funcs"]
    project__map["project.map<br/>36 funcs"]
    proposals["proposals<br/>2 funcs"]
    regulamin["regulamin<br/>1 funcs"]
    smoke_test["smoke-test<br/>8 funcs"]
    test_plesk["test-plesk<br/>3 funcs"]
