flowchart TD
    app["app<br/>14 funcs"]
    config_api["config-api<br/>3 funcs"]
    config_editor["config-editor<br/>4 funcs"]
    email_notifications["email-notifications<br/>4 funcs"]
    index["index<br/>7 funcs"]
    nda_form["nda-form<br/>3 funcs"]
    propozycje["propozycje<br/>2 funcs"]
    vendor__composer["vendor.composer<br/>42 funcs"]
    vendor__phpmailer["vendor.phpmailer<br/>190 funcs"]
