"""Batch autofix — scan, generate TODO.md, and fix all semcod packages.

Pipeline for each package:
1. If TODO.md exists with active issues → apply hybrid quality fixes
2. If no TODO.md or 0 active issues → scan with quality gate + analyzer, generate TODO.md
3. Run quality gate fix on remaining violations
4. Produce per-project and aggregate summary reports
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from ..analyzers import CodeAnalyzer
from ..autonomy.quality_gate import run_quality_gate, _collect_python_files, _measure_metrics
from ..formatters import format_batch_report_markdown

logger = logging.getLogger(__name__)

_MAX_TODO_ITEMS = 25
_MAX_GATE_TODO_ITEMS = 10

_SKIP_DIRS = frozenset({
    "venv", ".venv", ".git", "__pycache__", "node_modules", ".tox",
    "dist", "build", "logs", "2026", "project", "docs", "refactor_output",
    "shared", "pyqual-demo",
})

_PACKAGE_MARKERS = {"pyproject.toml", "setup.py", "setup.cfg"}


@dataclass
class ProjectFixResult:
    """Result of auto-fixing a single project."""

    name: str
    path: str
    had_todo: bool = False
    todo_issues_before: int = 0
    todo_issues_after: int = 0
    todo_generated: bool = False
    hybrid_applied: int = 0
    hybrid_errors: int = 0
    gate_violations: int = 0
    gate_fixed: int = 0
    gate_manual: int = 0
    py_files: int = 0
    total_loc: int = 0
    avg_cc: float = 0.0
    max_cc: int = 0
    critical_count: int = 0
    hotspots: list[tuple[str, int]] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    skipped: bool = False
    skip_reason: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_package(path: Path) -> bool:
    return any((path / m).exists() for m in _PACKAGE_MARKERS)


def _count_todo_issues(todo_file: Path) -> int:
    if not todo_file.exists():
        return 0
    content = todo_file.read_text(encoding="utf-8", errors="replace")
    return sum(1 for line in content.splitlines() if line.strip().startswith("- [ ]"))


def _append_gate_violations_to_todo(todo_file: Path, violations: list[str]) -> None:
    """Append quality gate violations to TODO.md."""
    existing = todo_file.read_text(encoding="utf-8") if todo_file.exists() else ""
    limited_violations = violations[:_MAX_GATE_TODO_ITEMS]
    section = "\n## Quality Gate Violations (auto-detected)\n\n"
    new_items = []
    for v in limited_violations:
        new_items.append(f"- [ ] {v}")
    dropped = len(violations) - len(limited_violations)
    if dropped > 0:
        new_items.append(f"- [ ] ... truncated {dropped} additional gate violations to keep autonomous runs bounded")
    if "## Quality Gate Violations (auto-detected)" in existing:
        # Replace existing section
        import re
        existing = re.sub(
            r"\n## Quality Gate Violations \(auto-detected\)\n(?:- \[ \].*\n?)*",
            "",
            existing,
            flags=re.MULTILINE,
        )
    todo_file.write_text(
        existing.rstrip() + section + "\n".join(new_items) + "\n",
        encoding="utf-8",
    )


def _find_packages(semcod_root: Path) -> list[Path]:
    """Find all packages in semcod root, sorted by name."""
    packages = []
    for item in sorted(semcod_root.iterdir()):
        if not item.is_dir():
            continue
        if item.name.startswith("."):
            continue
        if item.name in _SKIP_DIRS:
            continue
        if _is_package(item):
            packages.append(item)
    return packages


# ---------------------------------------------------------------------------
# TODO.md generator from scan findings
# ---------------------------------------------------------------------------

def _generate_todo_md(project: Path, metrics: dict, gate_violations: list[str]) -> str:
    """Generate a TODO.md from quality metrics and gate violations."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# TODO — {project.name}",
        "",
        f"> Auto-generated by reDSL on {now}",
        "",
    ]

    # Section: Critical functions (CC > 10)
    critical_funcs = [
        f for f in metrics.get("functions", [])
        if f["cc"] > 10
    ]
    if critical_funcs:
        lines += ["## High Complexity Functions", ""]
        for func in sorted(critical_funcs, key=lambda x: -x["cc"])[:_MAX_TODO_ITEMS]:
            lines.append(
                f"- [ ] Refactor `{func['name']}` in `{func['path']}` — CC={func['cc']} (line {func['lineno']})"
            )
        if len(critical_funcs) > _MAX_TODO_ITEMS:
            lines.append(f"- [ ] ... truncated {len(critical_funcs) - _MAX_TODO_ITEMS} more high-complexity functions")
        lines.append("")

    # Section: Large files (> 400 LOC)
    large_files = [
        f for f in metrics.get("files", [])
        if f["lines"] > 400
    ]
    if large_files:
        lines += ["## Large Files (>400 LoC)", ""]
        for fd in sorted(large_files, key=lambda x: -x["lines"])[:_MAX_TODO_ITEMS]:
            lines.append(f"- [ ] Split `{fd['path']}` — {fd['lines']} lines")
        if len(large_files) > _MAX_TODO_ITEMS:
            lines.append(f"- [ ] ... truncated {len(large_files) - _MAX_TODO_ITEMS} more large files")
        lines.append("")

    # Section: Quality gate violations
    if gate_violations:
        lines += ["## Quality Gate Violations", ""]
        for v in gate_violations[:_MAX_GATE_TODO_ITEMS]:
            lines.append(f"- [ ] {v}")
        if len(gate_violations) > _MAX_GATE_TODO_ITEMS:
            lines.append(f"- [ ] ... truncated {len(gate_violations) - _MAX_GATE_TODO_ITEMS} more gate violations")
        lines.append("")

    # Section: Moderate complexity (5 < CC <= 10)
    moderate_funcs = [
        f for f in metrics.get("functions", [])
        if 5 < f["cc"] <= 10
    ]
    if moderate_funcs:
        lines += ["## Moderate Complexity Functions", ""]
        for func in sorted(moderate_funcs, key=lambda x: -x["cc"])[:_MAX_TODO_ITEMS]:
            lines.append(
                f"- [ ] Simplify `{func['name']}` in `{func['path']}` — CC={func['cc']}"
            )
        if len(moderate_funcs) > _MAX_TODO_ITEMS:
            lines.append(f"- [ ] ... truncated {len(moderate_funcs) - _MAX_TODO_ITEMS} more moderate-complexity functions")
        lines.append("")

    # Section: Missing tests (heuristic)
    has_tests = any(project.rglob("test_*.py")) or any(project.rglob("*_test.py"))
    if not has_tests:
        lines += [
            "## Missing Tests",
            "",
            "- [ ] Add test suite — no test files found",
            "",
        ]

    # If nothing found, add a "clean" note
    if not any(line.startswith("- [ ]") for line in lines):
        lines += [
            "## Status",
            "",
            "- [x] No issues found — project is clean!",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hybrid quality fix (no LLM, direct refactorings)
# ---------------------------------------------------------------------------

def _run_hybrid_fix(project: Path, max_changes: int = 30) -> tuple[int, int]:
    """Apply hybrid quality refactorings. Returns (applied, errors)."""
    try:
        from ..dsl import RefactorAction
        from ..orchestrator import RefactorOrchestrator
        from ..config import AgentConfig
        from ..execution import _execute_direct_refactor

        quality_actions = [
            RefactorAction.REMOVE_UNUSED_IMPORTS,
            RefactorAction.FIX_MODULE_EXECUTION_BLOCK,
            RefactorAction.EXTRACT_CONSTANTS,
            RefactorAction.ADD_RETURN_TYPES,
        ]

        config = AgentConfig()
        config.refactor.apply_changes = True
        config.refactor.reflection_rounds = 0

        orchestrator = RefactorOrchestrator(config)
        analyzer = CodeAnalyzer()

        analysis = analyzer.analyze_project(project)
        contexts = analysis.to_dsl_contexts()
        all_decisions = orchestrator.dsl_engine.evaluate(contexts)

        quality_decisions = [d for d in all_decisions if d.action in quality_actions]
        quality_decisions.sort(key=lambda d: d.score, reverse=True)

        applied = 0
        errors = 0
        for decision in quality_decisions[:max_changes]:
            try:
                result = _execute_direct_refactor(orchestrator, decision, project)
                if result.applied:
                    applied += 1
                else:
                    errors += 1
            except Exception as exc:
                logger.debug("Fix failed for %s: %s", decision.target_file, exc)
                errors += 1

        return applied, errors
    except Exception as exc:
        logger.warning("Hybrid fix failed for %s: %s", project.name, exc)
        return 0, 1


# ---------------------------------------------------------------------------
# Single project pipeline
# ---------------------------------------------------------------------------

def _process_project(project: Path, max_changes: int = 30) -> ProjectFixResult:
    """Full autofix pipeline for a single project."""
    result = ProjectFixResult(name=project.name, path=str(project))

    # 1. Collect metrics
    try:
        py_files = _collect_python_files(project)
        metrics = _measure_metrics(project, py_files)
        result.py_files = metrics["total_files"]
        result.total_loc = metrics["total_lines"]
        result.avg_cc = round(metrics["cc_mean"], 2)
        result.critical_count = metrics["critical"]
        if metrics.get("functions"):
            result.max_cc = max(f["cc"] for f in metrics["functions"])
            result.hotspots = [
                (f["path"], f["cc"])
                for f in sorted(metrics["functions"], key=lambda x: -x["cc"])[:5]
                if f["cc"] > 5
            ]
    except Exception as exc:
        result.errors.append(f"Metrics: {exc}")
        metrics = {"functions": [], "files": []}

    # 2. Check TODO.md
    todo_file = project / "TODO.md"
    result.had_todo = todo_file.exists()
    result.todo_issues_before = _count_todo_issues(todo_file)

    # 3. If no TODO.md or empty → generate from scan
    if not result.had_todo or result.todo_issues_before == 0:
        print(f"    Generating TODO.md from scan findings...")
        try:
            gate_verdict = run_quality_gate(project)
            gate_violations = gate_verdict.violations
        except Exception:
            gate_violations = []

        todo_content = _generate_todo_md(project, metrics, gate_violations)
        todo_file.write_text(todo_content, encoding="utf-8")
        result.todo_generated = True
        result.todo_issues_before = _count_todo_issues(todo_file)
        print(f"    Generated TODO.md with {result.todo_issues_before} issues")

    # 4. Apply hybrid quality fixes
    if result.todo_issues_before > 0 or result.critical_count > 0:
        print(f"    Applying hybrid quality fixes (max {max_changes})...")
        applied, errors = _run_hybrid_fix(project, max_changes)
        result.hybrid_applied = applied
        result.hybrid_errors = errors
        if applied > 0:
            print(f"    Applied {applied} fixes ({errors} errors)")

    # 5. Run quality gate check (non-LLM: record violations in TODO.md)
    try:
        gate_verdict = run_quality_gate(project)
        result.gate_violations = len(gate_verdict.violations)
        if gate_verdict.violations:
            print(f"    Quality gate: {len(gate_verdict.violations)} violations → appending to TODO.md")
            _append_gate_violations_to_todo(todo_file, gate_verdict.violations)
            result.gate_manual = len(gate_verdict.violations)
        else:
            print(f"    Quality gate: PASSED")
    except Exception as exc:
        result.errors.append(f"Gate: {exc}")

    # 6. Run pyqual gates (if pyqual.yaml exists and pyqual CLI available)
    pyqual_yaml = project / "pyqual.yaml"
    if pyqual_yaml.exists():
        try:
            from ..validation.pyqual_bridge import is_available as pyqual_available, check_gates
            if pyqual_available():
                gate_result = check_gates(project)
                if gate_result.get("available"):
                    passed = gate_result.get("passed", True)
                    print(f"    pyqual gates: {'PASS' if passed else 'FAIL'}")
        except Exception as exc:
            logger.debug("pyqual bridge: %s", exc)

    # 7. Re-count TODO issues after fixes
    result.todo_issues_after = _count_todo_issues(todo_file)

    return result


# ---------------------------------------------------------------------------
# Batch runner
# ---------------------------------------------------------------------------

def run_autofix_batch(
    semcod_root: Path,
    max_changes: int = 30,
) -> dict[str, Any]:
    """Run full autofix pipeline on all semcod packages."""
    packages = _find_packages(semcod_root)
    print(f"\nFound {len(packages)} packages in {semcod_root}")
    print(f"Max changes per project: {max_changes}")
    print("=" * 60)

    all_results: list[ProjectFixResult] = []

    for i, package in enumerate(packages, 1):
        print(f"\n[{i}/{len(packages)}] {package.name}")
        print("-" * 40)

        result = _process_project(package, max_changes)
        all_results.append(result)

        # Brief status
        reduction = result.todo_issues_before - result.todo_issues_after
        status_parts = []
        if result.todo_generated:
            status_parts.append(f"TODO generated ({result.todo_issues_before} issues)")
        if result.hybrid_applied > 0:
            status_parts.append(f"{result.hybrid_applied} hybrid fixes")
        if result.gate_fixed > 0:
            status_parts.append(f"{result.gate_fixed} gate fixes")
        if reduction > 0:
            status_parts.append(f"TODO: {result.todo_issues_before}→{result.todo_issues_after}")
        if not status_parts:
            status_parts.append("no changes needed")

        print(f"  → {', '.join(status_parts)}")

    # Summary
    summary = _build_summary(all_results)
    _print_summary(summary, all_results)
    _save_reports(all_results, summary, semcod_root)

    return summary


def _build_summary(results: list[ProjectFixResult]) -> dict[str, Any]:
    return {
        "projects_processed": len(results),
        "todos_generated": sum(1 for r in results if r.todo_generated),
        "total_hybrid_applied": sum(r.hybrid_applied for r in results),
        "total_hybrid_errors": sum(r.hybrid_errors for r in results),
        "total_gate_violations": sum(r.gate_violations for r in results),
        "total_gate_fixed": sum(r.gate_fixed for r in results),
        "total_gate_manual": sum(r.gate_manual for r in results),
        "total_before": sum(r.todo_issues_before for r in results),
        "total_after": sum(r.todo_issues_after for r in results),
        "total_applied": sum(r.hybrid_applied + r.gate_fixed for r in results),
        "total_errors": sum(len(r.errors) for r in results),
        "project_details": [
            {
                "name": r.name,
                "path": r.path,
                "had_todo": r.had_todo,
                "todo_generated": r.todo_generated,
                "before_issues": r.todo_issues_before,
                "after_issues": r.todo_issues_after,
                "hybrid_applied": r.hybrid_applied,
                "gate_fixed": r.gate_fixed,
                "gate_manual": r.gate_manual,
                "py_files": r.py_files,
                "total_loc": r.total_loc,
                "avg_cc": r.avg_cc,
                "max_cc": r.max_cc,
                "critical_count": r.critical_count,
                "errors": r.errors,
            }
            for r in results
        ],
    }


def _print_summary(summary: dict[str, Any], results: list[ProjectFixResult]) -> None:
    print(f"\n{'=' * 60}")
    print("reDSL AUTOFIX SUMMARY")
    print(f"{'=' * 60}")
    print(f"Projects processed:   {summary['projects_processed']}")
    print(f"TODOs generated:      {summary['todos_generated']}")
    print(f"Hybrid fixes applied: {summary['total_hybrid_applied']}")
    print(f"Gate fixes applied:   {summary['total_gate_fixed']}")
    print(f"Gate manual needed:   {summary['total_gate_manual']}")
    print(f"TODO issues before:   {summary['total_before']}")
    print(f"TODO issues after:    {summary['total_after']}")
    reduction = summary["total_before"] - summary["total_after"]
    if reduction > 0:
        print(f"Total reduction:      {reduction} issues")
    if summary["total_errors"] > 0:
        print(f"Errors:               {summary['total_errors']}")

    # Top improvers
    improved = sorted(results, key=lambda r: r.todo_issues_before - r.todo_issues_after, reverse=True)
    top = [r for r in improved[:5] if r.todo_issues_before - r.todo_issues_after > 0]
    if top:
        print(f"\nTop improvements:")
        for r in top:
            red = r.todo_issues_before - r.todo_issues_after
            print(f"  {r.name}: {r.todo_issues_before}→{r.todo_issues_after} ({red} fewer)")


def _save_reports(results: list[ProjectFixResult], summary: dict[str, Any], semcod_root: Path) -> None:
    """Save markdown summary report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# reDSL Autofix Report",
        "",
        f"> Generated: **{now}**  ",
        f"> Root: `{semcod_root}`  ",
        f"> Projects: **{summary['projects_processed']}**",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|------:|",
        f"| Projects processed | {summary['projects_processed']} |",
        f"| TODOs generated | {summary['todos_generated']} |",
        f"| Hybrid fixes applied | {summary['total_hybrid_applied']} |",
        f"| Gate fixes applied | {summary['total_gate_fixed']} |",
        f"| Gate manual needed | {summary['total_gate_manual']} |",
        f"| TODO issues before | {summary['total_before']} |",
        f"| TODO issues after | {summary['total_after']} |",
        f"| Reduction | {summary['total_before'] - summary['total_after']} |",
        "",
        "---",
        "",
        "## Per-Project Details",
        "",
        "| # | Project | Files | LoC | CC̄ | CCmax | TODO⁰ | TODO¹ | Fixes | Status |",
        "|---|---------|------:|----:|----:|------:|------:|------:|------:|--------|",
    ]

    for i, r in enumerate(results, 1):
        fixes = r.hybrid_applied + r.gate_fixed
        status = "✅ generated" if r.todo_generated else ("✅ fixed" if fixes > 0 else "— clean")
        lines.append(
            f"| {i} | `{r.name}` | {r.py_files} | {r.total_loc:,} | {r.avg_cc:.1f} | {r.max_cc} "
            f"| {r.todo_issues_before} | {r.todo_issues_after} | {fixes} | {status} |"
        )

    lines += [
        "",
        "---",
        "",
        f"_Report generated by [reDSL](https://github.com/wronai/redsl)_",
    ]

    report_path = semcod_root / "redsl_autofix_report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nReport saved to: {report_path}")
