"""
Tier 3C — Behavioral Test Generator (code2logic integration).

Używa code2logic do:
  • generowania Gherkin BDD testów z CFG/DFG przed refaktoryzacją
  • snapshot testów pytest per ścieżka wykonania
  • weryfikacji zachowania po refaktoryzacji (porównanie CFG/DFG)

Jeśli code2logic nie jest zainstalowany, moduł gracefully degraduje —
generuje minimalne testy na podstawie własnej analizy AST.
"""

from __future__ import annotations

import ast
import logging
import subprocess
import textwrap
from pathlib import Path

try:
    import yaml as _yaml
    _YAML_AVAILABLE = True
except ImportError:
    _YAML_AVAILABLE = False

logger = logging.getLogger(__name__)


def _code2logic_available() -> bool:
    try:
        result = subprocess.run(
            ["code2logic", "--version"],
            capture_output=True,
            timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _run_code2logic(
    file_path: Path,
    function_name: str,
    fmt: str = "yaml",
    extra_args: list[str] | None = None,
) -> str:
    cmd = [
        "code2logic",
        str(file_path),
        "--function", function_name,
        "--format", fmt,
    ] + (extra_args or [])

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        logger.debug("code2logic failed for %s::%s: %s", file_path, function_name, result.stderr[:200])
        return ""
    return result.stdout


def _ast_fallback_paths(file_path: Path, function_name: str) -> list[dict]:
    """Fallback: parsuj AST i wyodrębnij podstawowe ścieżki (branch count)."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (OSError, SyntaxError):
        return []

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name == function_name:
                branches = sum(
                    1 for n in ast.walk(node)
                    if isinstance(n, (ast.If, ast.For, ast.While, ast.ExceptHandler, ast.With))
                )
                paths = [{"description": "happy path", "input_conditions": "nominal inputs"}]
                if branches > 0:
                    paths.append({"description": "error/edge path", "input_conditions": "edge-case inputs"})
                return paths
    return [{"description": "default path", "input_conditions": "any input"}]


def generate_behavior_tests(
    file_path: Path,
    function_name: str,
) -> str:
    """Wygeneruj Gherkin testy z analizy flow — uruchom PRZED refaktoryzacją.

    Returns Gherkin feature text, or empty string on failure.
    """
    if not _code2logic_available():
        logger.info("code2logic not found — generating minimal Gherkin via AST fallback")
        paths = _ast_fallback_paths(file_path, function_name)
        return _minimal_gherkin(file_path, function_name, paths)

    output = _run_code2logic(file_path, function_name, fmt="gherkin")
    if not output:
        paths = _ast_fallback_paths(file_path, function_name)
        return _minimal_gherkin(file_path, function_name, paths)
    return output


def _minimal_gherkin(file_path: Path, function_name: str, paths: list[dict]) -> str:
    lines = [
        f"Feature: {function_name} behavior",
        f"  # Auto-generated by ReDSL before refactoring {file_path.name}",
        "",
    ]
    for i, path in enumerate(paths):
        lines += [
            f"  Scenario: {path['description']}",
            f"    Given {path.get('input_conditions', 'valid inputs')}",
            f"    When {function_name} is called",
            f"    Then it should complete without error",
            "",
        ]
    return "\n".join(lines)


def generate_snapshot_test(
    file_path: Path,
    function_name: str,
    test_inputs: list[dict] | None = None,
) -> str:
    """Wygeneruj plik pytest z test cases per ścieżka wykonania."""
    cfg = _get_control_flow(file_path, function_name)
    paths = cfg.get("paths") or _ast_fallback_paths(file_path, function_name)

    module_import = file_path.stem

    test_lines = [
        "import pytest",
        f"from {module_import} import {function_name}",
        "",
        "",
        f"class TestBehaviorPreserved_{function_name}:",
        '    """Auto-generated by ReDSL before refactoring.',
        "    These tests verify behavior is preserved after changes.\"\"\"",
        "",
    ]

    for i, path in enumerate(paths):
        test_lines += [
            f"    def test_path_{i}(self):",
            f'        """Path: {path.get("description", f"path {i}")}"""',
            f"        # Input conditions: {path.get('input_conditions', 'N/A')}",
            "        # TODO: Add specific assertions based on domain knowledge",
            "        pass",
            "",
        ]

    return "\n".join(test_lines)


def verify_behavior_preserved(
    original_file: Path,
    refactored_file: Path,
    function_name: str,
) -> dict:
    """Porównaj CFG/DFG przed i po — czy zachowanie się nie zmieniło?

    Returns dict with keys:
      behavior_preserved, paths_before, paths_after,
      inputs_match, outputs_match, warnings.
    """
    original_cfg = _get_control_flow(original_file, function_name)
    refactored_cfg = _get_control_flow(refactored_file, function_name)

    paths_before = len(original_cfg.get("paths", []))
    paths_after = len(refactored_cfg.get("paths", []))

    original_dfg = _get_data_flow(original_file, function_name)
    refactored_dfg = _get_data_flow(refactored_file, function_name)

    inputs_match = set(original_dfg.get("inputs", [])) == set(refactored_dfg.get("inputs", []))
    outputs_match = set(original_dfg.get("outputs", [])) == set(refactored_dfg.get("outputs", []))

    warnings = _detect_behavioral_changes(original_cfg, refactored_cfg)

    return {
        "behavior_preserved": inputs_match and outputs_match,
        "paths_before": paths_before,
        "paths_after": paths_after,
        "inputs_match": inputs_match,
        "outputs_match": outputs_match,
        "warnings": warnings,
    }


def _get_control_flow(file_path: Path, function_name: str) -> dict:
    """Pobierz CFG z code2logic lub AST fallback."""
    if not _code2logic_available():
        paths = _ast_fallback_paths(file_path, function_name)
        return {"paths": paths}

    output = _run_code2logic(file_path, function_name, fmt="yaml")
    if not output:
        return {"paths": _ast_fallback_paths(file_path, function_name)}

    if _YAML_AVAILABLE:
        try:
            return _yaml.safe_load(output) or {}
        except Exception:
            pass
    return {}


def _get_data_flow(file_path: Path, function_name: str) -> dict:
    """Pobierz DFG z code2logic lub AST fallback."""
    if not _code2logic_available():
        return _ast_fallback_dfg(file_path, function_name)

    output = _run_code2logic(file_path, function_name, fmt="yaml", extra_args=["--dfg"])
    if not output:
        return _ast_fallback_dfg(file_path, function_name)

    if _YAML_AVAILABLE:
        try:
            return _yaml.safe_load(output) or {}
        except Exception:
            pass
    return {}


def _ast_fallback_dfg(file_path: Path, function_name: str) -> dict:
    """Fallback DFG — wyciągnij parametry i zwracane wartości z AST."""
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (OSError, SyntaxError):
        return {}

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name == function_name:
                inputs = [arg.arg for arg in node.args.args if arg.arg != "self"]
                outputs = []
                for n in ast.walk(node):
                    if isinstance(n, ast.Return) and n.value is not None:
                        if isinstance(n.value, ast.Name):
                            outputs.append(n.value.id)
                        else:
                            outputs.append("__return__")
                return {"inputs": inputs, "outputs": list(set(outputs))}
    return {}


def _detect_behavioral_changes(original: dict, refactored: dict) -> list[str]:
    """Wykryj zmiany w zachowaniu między CFG."""
    warnings = []
    orig_paths = len(original.get("paths", []))
    ref_paths = len(refactored.get("paths", []))

    if ref_paths > 0 and ref_paths < orig_paths:
        warnings.append(
            f"Reduced execution paths: {orig_paths} → {ref_paths} (possible lost behavior)"
        )
    elif orig_paths > 0 and ref_paths > orig_paths * 1.5:
        warnings.append(
            f"Added many execution paths: {orig_paths} → {ref_paths} (increased complexity?)"
        )
    return warnings
